// Synthetic question bank for the demo seed. The fake question generator
// returns these in order; the fake benchmark models answer them with a
// strong, partial or mistaken answer so the result screens show a spread.

export type DemoQuestion = {
  /** Words used to pick the matching textbook chunks from the retrieved evidence. */
  keywords: string[];
  searchQuery: string;
  targetConceptQuery: string;
  prerequisiteQuery: string;
  directionSummary: string;
  questionText: string;
  answerText: string;
  acceptedAnswers: string[];
  designSummary: string;
  evidenceSummary: string;
  targetConcept: string;
  prerequisites: Array<{ concept: string; role: string }>;
  relationExplanation: string;
  reasoningSteps: string[];
  failureSignals: string[];
  partialAnswer: string;
  mistakenAnswer: string;
};

export const DEMO_QUESTION_BANK: Record<'science' | 'math', DemoQuestion[]> = {
  science:[
    {
      keywords:['옴의 법칙', '전압', '저항', '전류의 세기'],
      searchQuery:'옴의 법칙에서 전압과 저항이 전류의 세기를 결정하는 관계',
      targetConceptQuery:'옴의 법칙',
      prerequisiteQuery:'전압과 전기 저항의 뜻',
      directionSummary:'전압과 저항의 의미를 먼저 적용해 전류 변화를 판단하게 한다.',
      questionText:'같은 전지에 연결한 니크롬선의 길이를 두 배로 늘렸더니 전류계의 눈금이 작아졌다. 전기 저항과 전압의 뜻을 이용하여 전류의 세기가 작아진 까닭을 옴의 법칙으로 설명하시오.',
      answerText:'같은 물질의 도선은 길이가 길수록 저항이 커지므로 니크롬선의 저항이 커졌다. 같은 전지를 사용했으므로 전압은 일정하다. 옴의 법칙(V = IR)에 따르면 전압이 일정할 때 전류의 세기는 저항에 반비례하므로 전류의 세기가 작아진다.',
      acceptedAnswers:['저항이 커져서 전압이 일정할 때 전류가 반비례하여 작아진다'],
      designSummary:'길이에 따른 저항 변화를 먼저 판단하고 옴의 법칙에 적용해야 풀리는 문항',
      evidenceSummary:'도선 길이와 저항의 관계, 옴의 법칙',
      targetConcept:'옴의 법칙',
      prerequisites:[
        { concept:'전기 저항', role:'도선 길이 변화가 저항을 키운다는 중간 결론을 만든다.' },
        { concept:'전압', role:'같은 전지를 쓰면 전압이 일정하다는 조건을 제공한다.' },
      ],
      relationExplanation:'저항과 전압의 변화를 먼저 판단해야 옴의 법칙으로 전류 변화를 설명할 수 있다.',
      reasoningSteps:['도선 길이 증가가 저항 증가임을 판단한다.', '전지가 같으므로 전압이 일정함을 확인한다.', '옴의 법칙으로 전류가 반비례하여 감소함을 결론짓는다.'],
      failureSignals:['저항이 커지면 전압이 작아진다고 답한다.', '길이와 저항의 관계를 언급하지 않는다.'],
      partialAnswer:'니크롬선이 길어지면 저항이 커지기 때문에 전류가 작아진다.',
      mistakenAnswer:'니크롬선이 길어지면 전하가 이동할 공간이 많아져 전압이 작아지고, 그래서 전류가 작아진다.',
    },
    {
      keywords:['직렬', '병렬', '전체 저항', '전압이 같고'],
      searchQuery:'저항의 직렬 연결과 병렬 연결에서 전류와 전압의 분배',
      targetConceptQuery:'저항의 병렬 연결',
      prerequisiteQuery:'전압과 옴의 법칙',
      directionSummary:'병렬 연결에서 전압이 같다는 조건을 옴의 법칙과 연결하게 한다.',
      questionText:'가정의 전기 기구는 모두 병렬로 연결되어 있다. 전기 기구를 하나 더 켜면 전체 저항과 전체 전류가 어떻게 변하는지, 각 기구에 걸리는 전압과 관련지어 설명하시오.',
      answerText:'병렬 연결에서는 각 기구에 걸리는 전압이 같으므로 기구를 추가해도 기존 기구의 전압은 변하지 않는다. 병렬로 저항을 추가하면 전체 저항은 작아지고, 전압이 일정할 때 옴의 법칙에 따라 전체 전류는 커진다.',
      acceptedAnswers:['전체 저항은 작아지고 전체 전류는 커진다'],
      designSummary:'병렬 연결의 전압 조건과 옴의 법칙을 결합해야 하는 문항',
      evidenceSummary:'직렬·병렬 연결의 특징과 옴의 법칙',
      targetConcept:'저항의 병렬 연결',
      prerequisites:[
        { concept:'옴의 법칙', role:'전압이 일정할 때 저항과 전류가 반비례함을 제공한다.' },
      ],
      relationExplanation:'옴의 법칙을 알아야 병렬 연결에서 전체 저항 감소가 전체 전류 증가로 이어짐을 판단할 수 있다.',
      reasoningSteps:['병렬 연결에서 각 기구의 전압이 같음을 확인한다.', '기구 추가로 전체 저항이 작아짐을 판단한다.', '옴의 법칙으로 전체 전류 증가를 결론짓는다.'],
      failureSignals:['기구를 추가하면 전체 저항이 커진다고 답한다.'],
      partialAnswer:'병렬로 기구를 더 켜면 전체 전류가 커진다.',
      mistakenAnswer:'기구를 더 연결하면 저항이 하나 더 생기므로 전체 저항이 커지고 전체 전류는 작아진다.',
    },
    {
      keywords:['열평형', '열량', '온도가 높은 물체', '체온계'],
      searchQuery:'열평형 상태에서 두 물체 사이 열 이동과 온도 변화',
      targetConceptQuery:'열평형',
      prerequisiteQuery:'열의 이동 방향과 온도',
      directionSummary:'열 이동 방향을 적용해 열평형 도달 과정을 설명하게 한다.',
      questionText:'80℃의 물이 담긴 컵을 20℃의 물이 담긴 수조에 넣어 두었다. 시간이 지나 두 물의 온도가 같아질 때까지 열의 이동 방향과 각 물의 온도 변화를 설명하고, 최종 상태를 무엇이라 하는지 쓰시오.',
      answerText:'열은 온도가 높은 컵 속 물에서 온도가 낮은 수조의 물로 이동한다. 그래서 컵 속 물의 온도는 내려가고 수조 물의 온도는 올라간다. 두 물의 온도가 같아지면 더 이상 열이 이동하지 않으며 이 상태를 열평형이라고 한다.',
      acceptedAnswers:['열평형'],
      designSummary:'열 이동 방향이라는 선수 개념을 적용해야 열평형을 설명할 수 있는 문항',
      evidenceSummary:'열의 이동 방향과 열평형의 정의',
      targetConcept:'열평형',
      prerequisites:[
        { concept:'열의 이동', role:'열이 고온에서 저온으로 이동한다는 방향을 제공한다.' },
      ],
      relationExplanation:'열의 이동 방향을 알아야 두 물체의 온도가 같아지는 열평형 과정을 설명할 수 있다.',
      reasoningSteps:['열이 고온에서 저온으로 이동함을 적용한다.', '각 물체의 온도 변화를 판단한다.', '온도가 같아진 상태를 열평형으로 명명한다.'],
      failureSignals:['차가움이 수조에서 컵으로 이동한다고 설명한다.'],
      partialAnswer:'두 물의 온도가 같아지는 상태를 열평형이라고 한다.',
      mistakenAnswer:'수조의 차가운 기운이 컵으로 이동해서 컵의 물이 식고, 두 물의 온도가 평균인 50℃가 되면 열평형이 된다.',
    },
    {
      keywords:['비열', '해안', '기온 변화', '온도 변화가 작다'],
      searchQuery:'비열이 큰 물질의 온도 변화와 해안 지역 기온',
      targetConceptQuery:'비열',
      prerequisiteQuery:'열량과 온도 변화',
      directionSummary:'열량과 온도 변화의 관계로 비열 차이를 해석하게 한다.',
      questionText:'여름 한낮에 해수욕장의 모래는 뜨겁지만 바닷물은 상대적으로 덜 뜨겁다. 같은 양의 햇빛을 받았다고 할 때 이 차이를 비열을 이용하여 설명하시오.',
      answerText:'모래와 바닷물은 같은 양의 열을 받았다. 비열은 물질 1kg의 온도를 1℃ 높이는 데 필요한 열량이므로, 비열이 큰 바닷물은 같은 열량을 받아도 온도 변화가 작고 비열이 작은 모래는 온도가 크게 오른다.',
      acceptedAnswers:['바닷물의 비열이 모래보다 커서 온도 변화가 작다'],
      designSummary:'같은 열량 조건에서 비열과 온도 변화의 관계를 적용하는 문항',
      evidenceSummary:'비열의 정의와 해안 지역 기온 변화 사례',
      targetConcept:'비열',
      prerequisites:[
        { concept:'열량', role:'두 물질이 받은 에너지의 양이 같다는 조건을 세운다.' },
      ],
      relationExplanation:'같은 열량을 받았다는 조건을 세워야 비열 차이로 온도 변화 차이를 설명할 수 있다.',
      reasoningSteps:['두 물질이 받은 열량이 같음을 확인한다.', '비열의 정의를 적용해 온도 변화를 비교한다.'],
      failureSignals:['바닷물이 햇빛을 덜 받았다고 설명한다.'],
      partialAnswer:'바닷물은 비열이 커서 잘 데워지지 않는다.',
      mistakenAnswer:'바닷물은 계속 움직이며 열을 밖으로 내보내기 때문에 모래보다 햇빛을 덜 흡수해서 덜 뜨겁다.',
    },
    {
      keywords:['이온', '전자를 잃', '양이온', '음이온'],
      searchQuery:'원자가 전자를 잃거나 얻어 이온이 되는 과정',
      targetConceptQuery:'이온의 형성',
      prerequisiteQuery:'원자의 구조와 전기적 중성',
      directionSummary:'원자가 전기적으로 중성인 이유를 먼저 적용해 이온의 전하를 판단하게 한다.',
      questionText:'나트륨 원자가 나트륨 이온(Na⁺)이 될 때 전하가 (+)가 되는 까닭을 원자의 구조와 전기적 중성을 이용하여 설명하시오.',
      answerText:'원자는 원자핵의 (+)전하량과 전자의 총 (-)전하량이 같아 전기적으로 중성이다. 나트륨 원자가 전자 1개를 잃으면 (-)전하가 하나 줄어 (+)전하량이 더 많아지므로 (+)전하를 띠는 양이온 Na⁺가 된다.',
      acceptedAnswers:['전자 1개를 잃어 양전하가 더 많아진다'],
      designSummary:'원자의 전기적 중성을 적용해야 이온의 전하를 설명할 수 있는 문항',
      evidenceSummary:'원자의 구조, 이온의 형성, 나트륨 이온 예시',
      targetConcept:'이온의 형성',
      prerequisites:[
        { concept:'원자의 구조', role:'원자핵과 전자의 전하량이 같아 중성이라는 출발점을 제공한다.' },
      ],
      relationExplanation:'원자가 중성인 이유를 알아야 전자를 잃었을 때 (+)전하를 띠는 이유를 설명할 수 있다.',
      reasoningSteps:['원자가 전기적으로 중성임을 확인한다.', '전자를 잃으면 (-)전하가 줄어듦을 적용한다.', '(+)전하를 띠는 양이온이 됨을 결론짓는다.'],
      failureSignals:['양성자를 얻어 (+)가 된다고 답한다.'],
      partialAnswer:'나트륨 원자가 전자를 잃어서 양이온이 된다.',
      mistakenAnswer:'나트륨 원자가 (+)전하를 띠는 양성자 1개를 얻어서 전체 전하가 (+)가 된다.',
    },
    {
      keywords:['코일', '전자석', '자기장', '전류의 세기가 셀수록'],
      searchQuery:'코일에 흐르는 전류와 전자석의 자기장 세기',
      targetConceptQuery:'전자석',
      prerequisiteQuery:'전류의 자기 작용',
      directionSummary:'전류가 자기장을 만든다는 원리를 전자석 세기 판단에 적용하게 한다.',
      questionText:'전자석으로 클립을 더 많이 들어 올리려고 한다. 전류가 흐르는 도선 주위에 생기는 자기장의 성질을 이용하여 전자석을 세게 만드는 방법 두 가지와 그 까닭을 설명하시오.',
      answerText:'전류가 흐르는 도선 주위에는 자기장이 생기고, 코일에 전류가 흐르면 내부에 막대자석과 비슷한 자기장이 생긴다. 전류의 세기를 크게 하거나 코일을 더 촘촘하게 감으면 코일 내부의 자기장이 세지므로 전자석이 더 많은 클립을 들어 올린다.',
      acceptedAnswers:['전류를 세게 하고 코일을 촘촘하게 감는다'],
      designSummary:'전류의 자기 작용을 전자석 설계 조건으로 전이하는 문항',
      evidenceSummary:'직선 도선과 코일의 자기장, 전자석',
      targetConcept:'전자석',
      prerequisites:[
        { concept:'전류의 자기 작용', role:'전류가 자기장을 만든다는 원리를 제공한다.' },
      ],
      relationExplanation:'전류가 자기장을 만든다는 원리를 알아야 전자석의 세기를 조절하는 조건을 설명할 수 있다.',
      reasoningSteps:['전류가 자기장을 만든다는 원리를 적용한다.', '코일 내부 자기장이 전류 세기와 감은 수에 따라 세짐을 판단한다.'],
      failureSignals:['도선을 굵게 하면 자기장이 세진다고만 답한다.'],
      partialAnswer:'전류를 세게 하면 전자석이 세진다.',
      mistakenAnswer:'코일을 느슨하게 감아 전류가 지나가는 길을 넓히면 자기장이 강해져 전자석이 세진다.',
    },
  ],
  math:[
    {
      keywords:['유한소수', '소인수', '분모', '2나 5'],
      searchQuery:'기약분수의 분모의 소인수와 유한소수 판별',
      targetConceptQuery:'유한소수 판별',
      prerequisiteQuery:'기약분수와 소인수분해',
      directionSummary:'기약분수로 고친 뒤 분모의 소인수를 판단하게 한다.',
      questionText:'분수 21/60을 소수로 나타낼 때 유한소수가 되는지 판별하고, 그 까닭을 기약분수와 분모의 소인수를 이용하여 쓰시오.',
      answerText:'21/60을 기약분수로 나타내면 7/20이다. 20 = 2² × 5이므로 분모의 소인수가 2와 5뿐이다. 따라서 21/60은 유한소수 0.35로 나타낼 수 있다.',
      acceptedAnswers:['유한소수', '0.35'],
      designSummary:'기약분수화와 소인수분해를 거쳐야 판별되는 문항',
      evidenceSummary:'유한소수가 되는 분수의 조건',
      targetConcept:'유한소수 판별',
      prerequisites:[
        { concept:'기약분수', role:'분모를 판단하기 전에 약분해야 한다는 조건을 제공한다.' },
        { concept:'소인수분해', role:'분모의 소인수가 2와 5뿐인지 확인하게 한다.' },
      ],
      relationExplanation:'기약분수로 고친 뒤 분모를 소인수분해해야 유한소수 여부를 판별할 수 있다.',
      reasoningSteps:['21/60을 7/20으로 약분한다.', '20을 2² × 5로 소인수분해한다.', '소인수가 2와 5뿐이므로 유한소수라고 판단한다.'],
      failureSignals:['약분하지 않고 60 = 2² × 3 × 5만 보고 순환소수라고 답한다.'],
      partialAnswer:'유한소수이다. 21/60 = 0.35이다.',
      mistakenAnswer:'60 = 2² × 3 × 5로 분모에 3이 있으므로 21/60은 순환소수가 된다.',
    },
    {
      keywords:['지수법칙', 'a^m', '지수끼리', '거듭제곱'],
      searchQuery:'지수법칙 거듭제곱의 곱셈과 거듭제곱의 거듭제곱',
      targetConceptQuery:'지수법칙',
      prerequisiteQuery:'거듭제곱의 뜻',
      directionSummary:'거듭제곱의 곱과 거듭제곱의 거듭제곱 규칙을 구분해 적용하게 한다.',
      questionText:'(2³)² × 2⁴을 2의 거듭제곱 꼴로 간단히 나타내고, 계산 과정에서 사용한 지수법칙을 순서대로 쓰시오.',
      answerText:'(2³)² = 2^(3×2) = 2⁶이다. 2⁶ × 2⁴ = 2^(6+4) = 2¹⁰이다. 따라서 답은 2¹⁰이며, 거듭제곱의 거듭제곱에서는 지수끼리 곱하고 같은 수의 거듭제곱끼리 곱할 때는 지수끼리 더한다.',
      acceptedAnswers:['2^10', '2¹⁰'],
      designSummary:'두 지수법칙을 순서대로 구분 적용해야 하는 문항',
      evidenceSummary:'지수법칙 세 가지',
      targetConcept:'지수법칙',
      prerequisites:[
        { concept:'거듭제곱', role:'같은 수를 여러 번 곱한 것을 지수로 나타낸다는 뜻을 제공한다.' },
      ],
      relationExplanation:'거듭제곱의 뜻을 알아야 지수를 더하는 경우와 곱하는 경우를 구분할 수 있다.',
      reasoningSteps:['(2³)²에 거듭제곱의 거듭제곱 법칙을 적용한다.', '2⁶ × 2⁴에 지수의 덧셈 법칙을 적용한다.'],
      failureSignals:['(2³)²를 2⁵로 계산한다.'],
      partialAnswer:'2¹⁰',
      mistakenAnswer:'(2³)² = 2⁵이고 2⁵ × 2⁴ = 2⁹이므로 답은 2⁹이다.',
    },
    {
      keywords:['부등호의 방향', '음수', '양변', '일차부등식'],
      searchQuery:'부등식의 양변에 음수를 곱하거나 나눌 때 부등호 방향',
      targetConceptQuery:'일차부등식의 풀이',
      prerequisiteQuery:'부등식의 성질',
      directionSummary:'음수로 나눌 때 부등호 방향이 바뀌는 성질을 풀이에 적용하게 한다.',
      questionText:'일차부등식 5 - 3x ≥ 14를 풀고, 풀이 과정에서 부등호의 방향이 바뀌는 단계와 그 까닭을 쓰시오.',
      answerText:'5를 이항하면 -3x ≥ 9이다. 양변을 -3으로 나누면 음수로 나누었으므로 부등호의 방향이 바뀌어 x ≤ -3이다. 따라서 해는 x ≤ -3이다.',
      acceptedAnswers:['x ≤ -3', 'x<=-3'],
      designSummary:'부등식의 성질을 적용해야 올바른 해를 얻는 문항',
      evidenceSummary:'부등식의 성질과 일차부등식의 풀이',
      targetConcept:'일차부등식의 풀이',
      prerequisites:[
        { concept:'부등식의 성질', role:'음수로 나누면 부등호 방향이 바뀐다는 규칙을 제공한다.' },
      ],
      relationExplanation:'부등식의 성질을 알아야 일차부등식을 풀 때 부등호 방향을 올바르게 정할 수 있다.',
      reasoningSteps:['상수항을 이항해 -3x ≥ 9로 정리한다.', '음수 -3으로 나누며 부등호 방향을 바꾼다.'],
      failureSignals:['x ≥ -3이라고 답한다.'],
      partialAnswer:'x ≤ -3',
      mistakenAnswer:'-3x ≥ 9의 양변을 -3으로 나누면 x ≥ -3이다.',
    },
    {
      keywords:['가감법', '연립일차방정식', '미지수를 없앤', '계수의 절댓값'],
      searchQuery:'가감법으로 연립일차방정식의 한 미지수 없애기',
      targetConceptQuery:'가감법',
      prerequisiteQuery:'등식의 성질과 계수 맞추기',
      directionSummary:'계수를 맞춘 뒤 한 미지수를 없애는 절차를 적용하게 한다.',
      questionText:'연립방정식 2x + 3y = 12, 3x - y = 7을 가감법으로 푸시오. 어떤 미지수를 없애기 위해 어떤 수를 곱했는지도 쓰시오.',
      answerText:'y를 없애기 위해 두 번째 식의 양변에 3을 곱하면 9x - 3y = 21이다. 첫 번째 식과 더하면 11x = 33이므로 x = 3이다. x = 3을 3x - y = 7에 대입하면 y = 2이다. 따라서 해는 x = 3, y = 2이다.',
      acceptedAnswers:['x = 3, y = 2', '(3, 2)'],
      designSummary:'계수 맞추기를 선행해야 가감법이 성립하는 문항',
      evidenceSummary:'가감법의 절차',
      targetConcept:'가감법',
      prerequisites:[
        { concept:'등식의 성질', role:'양변에 같은 수를 곱해도 등식이 성립함을 제공한다.' },
      ],
      relationExplanation:'등식의 성질로 계수를 맞춰야 가감법으로 한 미지수를 없앨 수 있다.',
      reasoningSteps:['두 번째 식에 3을 곱해 y의 계수를 맞춘다.', '두 식을 더해 x를 구한다.', 'x를 대입해 y를 구한다.'],
      failureSignals:['한쪽 항에만 3을 곱한다.'],
      partialAnswer:'x = 3, y = 2',
      mistakenAnswer:'두 번째 식의 y에만 3을 곱해 3x - 3y = 7로 만들고 더하면 5x = 19이므로 x = 19/5이다.',
    },
    {
      keywords:['기울기', 'y절편', '증가량', '오른쪽 아래'],
      searchQuery:'일차함수 그래프의 기울기와 y절편의 의미',
      targetConceptQuery:'일차함수의 기울기',
      prerequisiteQuery:'일차함수의 뜻과 증가량',
      directionSummary:'두 점의 증가량 비율로 기울기를 구하고 그래프 모양을 판단하게 한다.',
      questionText:'일차함수의 그래프가 두 점 (1, 5), (3, 1)을 지난다. 이 그래프의 기울기와 y절편을 구하고, 그래프가 오른쪽 위로 향하는지 오른쪽 아래로 향하는지 쓰시오.',
      answerText:'기울기는 (y의 값의 증가량)/(x의 값의 증가량) = (1 - 5)/(3 - 1) = -2이다. y = -2x + b에 (1, 5)를 대입하면 b = 7이므로 y절편은 7이다. 기울기가 음수이므로 그래프는 오른쪽 아래로 향한다.',
      acceptedAnswers:['기울기 -2, y절편 7, 오른쪽 아래'],
      designSummary:'증가량의 비율이라는 선수 개념을 적용해 기울기를 해석하는 문항',
      evidenceSummary:'기울기의 정의와 부호에 따른 그래프 모양, y절편',
      targetConcept:'일차함수의 기울기',
      prerequisites:[
        { concept:'일차함수', role:'y = ax + b 꼴과 대입으로 y절편을 구하는 방법을 제공한다.' },
      ],
      relationExplanation:'일차함수의 식을 알아야 증가량의 비율을 기울기로 해석하고 y절편을 구할 수 있다.',
      reasoningSteps:['두 점의 증가량 비율로 기울기를 구한다.', '한 점을 대입해 y절편을 구한다.', '기울기의 부호로 그래프 방향을 판단한다.'],
      failureSignals:['기울기를 (3 - 1)/(1 - 5)로 뒤집어 계산한다.'],
      partialAnswer:'기울기는 -2이고 그래프는 오른쪽 아래로 향한다.',
      mistakenAnswer:'기울기는 (3 - 1)/(1 - 5) = -1/2이고 y절편은 5이다.',
    },
    {
      keywords:['교점', '평행', '해가 없고', '일차방정식의 그래프'],
      searchQuery:'연립일차방정식의 해와 두 직선의 교점 평행',
      targetConceptQuery:'연립방정식의 해와 그래프',
      prerequisiteQuery:'일차방정식을 일차함수로 나타내기',
      directionSummary:'일차방정식을 일차함수 꼴로 바꿔 기울기를 비교하게 한다.',
      questionText:'연립방정식 x + 2y = 4, 2x + 4y = 3의 해의 개수를 그래프를 이용하여 판단하고, 그 까닭을 두 직선의 기울기와 y절편으로 설명하시오.',
      answerText:'두 식을 일차함수 꼴로 바꾸면 y = -1/2x + 2, y = -1/2x + 3/4이다. 기울기는 -1/2로 같고 y절편은 다르므로 두 직선은 평행하다. 따라서 교점이 없어 연립방정식의 해는 없다.',
      acceptedAnswers:['해가 없다'],
      designSummary:'일차방정식과 일차함수의 관계를 적용해 해의 개수를 판단하는 문항',
      evidenceSummary:'일차방정식의 그래프, 연립방정식의 해와 교점',
      targetConcept:'연립방정식의 해와 그래프',
      prerequisites:[
        { concept:'일차함수의 기울기', role:'두 직선이 평행한지 판단하는 기준을 제공한다.' },
      ],
      relationExplanation:'기울기와 y절편을 비교할 수 있어야 두 직선의 위치 관계로 해의 개수를 판단할 수 있다.',
      reasoningSteps:['두 방정식을 일차함수 꼴로 바꾼다.', '기울기와 y절편을 비교해 평행함을 판단한다.', '교점이 없으므로 해가 없다고 결론짓는다.'],
      failureSignals:['두 식이 비례하므로 해가 무수히 많다고 답한다.'],
      partialAnswer:'두 직선이 평행하므로 해가 없다.',
      mistakenAnswer:'두 번째 식이 첫 번째 식의 2배이므로 두 직선이 일치하여 해가 무수히 많다.',
    },
  ],
};
